### ISSUE TITLE
Why is a reverse proxy useful to improve the security of the infrastructure ?

### ISSUE THREAD

**Issue by nigelmann** [nigelmann/res-http#1]
Hello m8 !

There is just one part of the documentation we need to discuss.

https://github.com/HEIGVD-Course-API/API-2021-HTTP-Infra#step-4-ajax-requests-with-jquery

Maybe tomorrow you have a little time for that ? I would be gr8ful 

In the mean time if you have some spare time you can check the documentation. I have added the missing parts.

Cheers m8 !

**Comment by noahboegli** [comment]
Awesome labeling m8. Very good to classify the issues when searching what to work on !

I'll read the documentation tonight and we can discuss this issue tomorrow 

Cheers
